sudo: required
services:
  - docker

before_install:
  - docker build -t erickmckracken/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run erickmckracken/react-test npm test -- --coverage

after_success: 
  - docker build -t erickmckracken/multi-client ./client
  - docker build -t erickmckracken/multi-nginx ./nginx
  - docker build -t erickmckracken/multi-server ./server
  - docker build -t erickmckracken/multi-worker ./worker

  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those fuc************ images and push them to dockerhub
  - docker push erickmckracken/multi-client 
  - docker push erickmckracken/multi-nginx 
  - docker push erickmckracken/multi-server 
  - docker push erickmckracken/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: ca-central-1
  app: multi-docker4
  env: Multi-Docker4-env
  bucket_name: elasticbeanstalk-ca-central-1-676100722752
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY